trigger:
- main

pool: infra-pool-Automation

stages:
  - stage: Terraforminit
    jobs:
      - job: Terraforminit
        displayName: Terraforminit
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)Environment/Dev'
            backendServiceArm: 'slc'
            backendAzureRmResourceGroupName: 'sssss'
            backendAzureRmStorageAccountName: 'pppscshcs'
            backendAzureRmContainerName: 'dfjwwnqw'
            backendAzureRmKey: 'dev.terraform.tfstate'

